### ISSUE TITLE
License specification is missing

### ISSUE THREAD

**Issue by merkys** [ievaKer/pathExplore#4]
For the package to be usable, license specification is required. Currently, `DESCRIPTION` file contains mostly placeholder values, including:
```
License: What license is it under?
```
It would be nice to have a F/LOSS license for this package (i.e., BSD-3-Clause, MIT, LGPL-v3 just to name a few).

**Comment by ievaKer** [comment]
Thank you for the suggestion, I added the licence! :)

**Comment by merkys** [comment]
Thanks for adding the license!
